### ISSUE TITLE
Last details

### ISSUE THREAD

**Issue by sgillies** [geojson/ietf-92-presentation#2]
1. more on related work, especially OGC standards: OGC members have been participating in GeoJSON discussions, we're certain we're not duplicating work going on in the OGC.
2. completeness of I-D: note extension points are a TODO.
3. Indicate how many GeoJSON authors are willing to work on this (virtual show of hands).

**Comment by adoyle** [comment]
I'll raise my hand for #3.

**Comment by hobu** [comment]
Likewise, I'm up for supporting #3. Any tasks need specific activity not yet covered?

**Comment by sgillies** [comment]
@adoyle @hobu in tomorrow's session, the chairs will ask people to raise their hands if they are in for the work of forming and running a working group and the chairs are looking for a minimum number. I want to indicate that our number should be included even though we're not present.

**Comment by tschaub** [comment]
Raising my hand as willing to work on this.

**Comment by mpdaly** [comment]
I'm in.

**Comment by dret** [comment]
if you can make the call (in about 1.5hrs), it would be great to tune into the presentation and then hum for support (that's IETF's quirky way of asking for supporting votes). http://venetian.conf.meetecho.com/q-meetecho/login.jsp?ietf=dispatch is the virtual meeting room, please join if you can. thanks!

**Comment by sgillies** [comment]
GeoJSON is dispatched to RAI: http://trac.tools.ietf.org/area/rai/trac/wiki. Chartering to continue with the ADs.

**Comment by dret** [comment]
good job, @sgillies, thanks! next up: getting charter up to IETF standards.
